version: '3.7'
networks:
    ntk-app:
        driver: bridge
        name: ntk-app
services:
    lbctl-liburutegia:
        container_name: lbctl-liburutegia
        build: .
        restart: always
        environment:
            COVER_DIR: ${COVER_DIR}
            WEBDRIVER_HOST: ${WEBDRIVER_HOST}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PORT: ${MYSQL_PORT}
            REDIS_PORT: ${REDIS_PORT}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            REDIS_COMMANDER_PORT: ${REDIS_COMMANDER_PORT}
            BUCKET_NAME: ${BUCKET_NAME}
            USE_SSL: ${USE_SSL}
            MINIO_HOST: ${MINIO_HOST}
            MINIO_PORT: ${MINIO_PORT}
            MINIO_USER: ${MINIO_USER}
            MINIO_CONSOLE_PORT: ${MINIO_CONSOLE_PORT}
            MINIO_PASSWORD: ${MINIO_PASSWORD}
        volumes: 
          - ${COVER_DIR}:/app/covers-liburutegia
        #     - ${COVER_DIR}:/app/covers-prueba
        networks:
            - ntk-app
        command: "sh -c '$$@'"

